#deploy to framworkserver
name: Build and deploy to qpon prod server

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      #run: mvn -B clean install --file pom.xml
      run: mvn clean compile package #-DskipTests

  notify:
    if: "${{ failure() }}"
    runs-on: ubuntu-latest
    needs: build
    steps:      
    - uses: actions/checkout@v2
    - uses: iRoachie/slack-github-actions@v2.3.0
      with:
        status: ${{ job.status }}
        env:
          #SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          #curl -X POST -H 'Content-type: application/json' --data '{"text":"✅ {your-job-name-here} passed."}' ${{ secrets.SLACK_WEBHOOK_URL }}
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INCOMING_WEBHOOK_URL: https://hooks.slack.com/services/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
          text: ":heavy_check_mark: Build success - Deploy -  Server - TEST - Azure Web pps CI/CD. :heavy_check_mark:"
