#deploy to framworkserver
name: Build and Test the PR

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      #run: mvn -B clean install --file pom.xml
      run: mvn clean compile package #-DskipTests

    - name: Notify Slack about success
      if: success()
      #if: needs.build.result == 'success'
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: xoxb-2546478802199-2890421198983-UrEdMB3LFzHm0w8vbyejqVca
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: qpon
        payload: >-
          {
              "icon_emoji": ":rocket:",
              "username": "${{ github.event.sender.login }}",
              "text": "Build and Test success."
          }

    - name: Notify Slack about fail
      if: failure() 
      #if: needs.build.result == 'failure'
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: xoxb-2546478802199-2890421198983-UrEdMB3LFzHm0w8vbyejqVca
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: qpon
        payload: >-
          {
              "icon_emoji": ":boom:",
              "username": "${{ github.event.sender.login }}",
              "text": "Build and Test failed! Before submitting the PR, please build and execute the test locally."
          }

