#deploy to framworkserver
name: Build and deploy to qpon prod server

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      #run: mvn -B clean install --file pom.xml
      run: mvn clean compile package #-DskipTests

  notify:
  - name: Notify Slack about deployment fail
    if: failure() # You can use the conditional checks to determine which notification to send.
    uses: wearerequired/slack-messaging-action@v1
    with:
      bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      message_id: ${{ steps.slack.outputs.message_id }} # Updates existing message from the first step.
      channel: deployments
      payload: >-
        {
            "icon_emoji": ":boom:",
            "username": "Deployer",
            "t ext": "Deployment failed."
        }