#deploy to framworkserver
name: Build and deploy to qpon prod server

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      #run: mvn -B clean install --file pom.xml
      run: mvn clean compile package #-DskipTests

      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: xoxb-2546478802199-2890421198983-UrEdMB3LFzHm0w8vbyejqVca
        channel: qpon
        payload: >-
          {
              "icon_emoji": ":rocket:",
              "username": "Deployer",
              "attachments": [
                  {
                      "author_name": "${{ github.event.sender.login }}",
                      "author_link": "${{ github.event.sender.html_url }}",
                      "author_icon": "${{ github.event.sender.avatar_url }}",
                      "color": "good",
                      "fallback": "Deployment finished.",
                      "pretext": "Deployment finished.",
                      "fields": [
                          {
                            "title": "Revision",
                            "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}@${{ github.ref }}>",
                            "short": true
                          }
                      ],
                      "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>",
                  }
              ]
          }

    - name: Notify Slack about deployment start
      if: success()
      id: slack # IMPORTANT: Reference this step ID value in future Slack steps.
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: xoxb-2546478802199-2890421198983-UrEdMB3LFzHm0w8vbyejqVca
        channel: qpon
        payload: >-
          {
              "icon_emoji": ":rocket:",
              "username": "Deployer",
              "text": "Deployment started."
          }

    - name: Deployment

    - name: Notify Slack about deployment success
      if: success() # You can use the conditional checks to determine which notification to send.
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: xoxb-2546478802199-2890421198983-UrEdMB3LFzHm0w8vbyejqVca
        message_id: ${{ steps.slack.outputs.message_id }} # Updates existing message from the first step.
        channel: qpon
        payload: >-
          {
              "icon_emoji": ":rocket:",
              "username": "Deployer",
              "text": "Deployment finished."
          }

    - name: Notify Slack about deployment fail
      if: failure() # You can use the conditional checks to determine which notification to send.
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: xoxb-2546478802199-2890421198983-UrEdMB3LFzHm0w8vbyejqVca
        message_id: ${{ steps.slack.outputs.message_id }} # Updates existing message from the first step.
        channel: qpon
        payload: >-
          {
              "icon_emoji": ":boom:",
              "username": "Deployer",
              "text": "Deployment failed."
          }
