#deploy to framworkserver
name: notify

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    #  - uses: actions/checkout@v2
    #  - uses: iRoachie/slack-github-actions@v2.3.0
    #    with:
    #      status: ${{ job.status }}
    #    env:
    #      #SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    #      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #      status: ${{ job.status }}
    #    if: ${{ always() }}

      - uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: devopstest
          SLACK_MESSAGE: The build is failure
          #SLACK_TITLE: PR Request
          SLACK_USERNAME: ${{ github.event.sender.login }}
          #SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
